# Generated by Django 3.2.9 on 2021-11-12 08:36

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Hesap',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('isim', models.CharField(max_length=255)),
                ('email', models.CharField(max_length=255)),
                ('telefon', models.CharField(max_length=255)),
                ('unvan', models.CharField(max_length=255)),
                ('ozet', models.TextField()),
                ('resim', models.ImageField(upload_to='')),
            ],
        ),
    ]
